title: ""
title_short: ""
description: ""
keywords: ""
author: ""
logo: " "

navigation:
  - title: "Home"
    url: "/"

# Footer configuration
footer:
  columns:
    - title: "Quick Links"
      links:
        - name: "Home"
          url: "/"
